import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import NavbarAlt from "./components/navbarAlt/navbarAlt";
import Footer from "./components/footer/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Navbar />
        <NavbarAlt />
        {children}
        <Footer />
      </body>
    </html>
  );
}
