export const dataCard = [
  {
    image: "/img/Summer-Scene-Light.png",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    size: ["xxl", "xl"],
    tags: ["Female", "T-Shirt"],
  },
  {
    image: "/img/Summer-Scene-Light.png",
    alt: "alt image",
    title: "Placeholder title 2",
    description: "Placeholder description for 2",
    link: "/",
    price: 99,
    size: ["lg"],
    tags: ["Male", "Pants"],
  },
  {
    image: "/img/Summer-Scene-Light.png",
    alt: "alt image",
    title: "Placeholder title 3",
    description: "Placeholder description for 3",
    link: "/",
    price: 20,
    size: ["l", "m"],
    tags: ["Test", "test"],
  },
  {
    image: "/img/Summer-Scene-Light.png",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 120,
    size: ["xxl", "xl"],
    tags: ["Test", "test"],
  },
  {
    image: "/img/Summer-Scene-Light.png",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 30,
    size: ["xxl", "xl"],
    tags: ["Test", "test"],
  },
  {
    image: "/img/Summer-Scene-Light.png",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 40,
    size: ["xxl", "xl"],
    tags: ["Test", "test"],
  },
  {
    image: "/img/Summer-Scene-Light.png",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    size: ["xxl", "xl"],
    tags: ["Test", "test"],
  },
  {
    image: "/img/Summer-Scene-Light.png",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    size: ["xxl", "xl"],
    tags: ["Test", "test"],
  },
];
