export const dataCard = [
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    size: ["xxl"],
    tags: ["Female", "T-Shirt"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    size: ["xxl"],
    tags: ["Female", "T-Shirt"],
    for: "ado",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 200,
    size: ["xxl"],
    tags: ["Female", "T-Shirt"],
    for: "ado",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 2",
    description: "Placeholder description for 2",
    link: "/",
    price: 99,
    size: ["lg"],
    tags: ["Male", "Pants"],
    for: "femme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 3",
    description: "Placeholder description for 3",
    link: "/",
    price: 20,
    size: ["l", "m"],
    tags: ["Test", "test"],
    for: "enfant",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 120,
    size: ["xxl", "xl"],
    tags: ["Test", "test"],
    for: "enfant",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 30,
    size: ["xxl", "xl"],
    tags: ["Test", "test"],
    for: "enfant",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 40,
    size: ["xxl", "xl"],
    tags: ["Test", "test"],
    for: "enfant",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    size: ["xxl", "xl"],
    tags: ["Test", "test"],
    for: "enfant",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    size: ["xxl", "xl"],
    tags: ["Test", "test"],
    for: "enfant",
  },
];
