export const dataCard = [
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["garçon", "T-Shirt"],
    gender: "garcon",
    for: "enfant",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["Ado", "T-Shirt", "xxl"],
    gender: "garcon",
    for: "ado",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 200,
    tags: ["garcon", "Ado"],
    gender: "garcon",
    for: "ado",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 2",
    description: "Placeholder description for 2",
    link: "/",
    price: 99,
    tags: ["Fille", "Pants"],
    gender: "fille",
    for: "enfant",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 3",
    description: "Placeholder description for 3",
    link: "/",
    price: 20,
    tags: ["l", "m"],
    gender: "fille",
    for: "enfant",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 120,
    tags: ["xxl", "xl"],
    for: "enfant",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 30,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 40,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "enfant",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
  {
    image: "/img/placeholder_product.jpg",
    alt: "alt image",
    title: "Placeholder title 1",
    description: "Placeholder description for 1",
    link: "/",
    price: 20,
    tags: ["xxl", "xl"],
    for: "homme",
  },
];
